# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AUTO_TASK_FOR_BILIBILI

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时


jobs:
  start:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          CONFIG: ${{ secrets.CONFIG }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run:
          echo ${CONFIG} > config.json;
          mvn -B package --file pom.xml;
          mv -f target/BILIBILI-HELPER-*.jar .;
          java -jar BILIBILI-HELPER-*.jar;
